In [142]:
#NAMA/NIM = William Andrian Dharma T / 19623048
#TANGGAL = 16/11/23
#DESKRIPSI = Program analisis data

In [143]:
import pandas as pd
import matplotlib as mat
df = pd.read_csv('P05-03.csv')

In [144]:
#nomor 1
df['neighbourhood_group'].value_counts()

neighbourhood_group
Central Region       6309
West Region           540
East Region           508
North-East Region     346
North Region          204
Name: count, dtype: int64

In [145]:
#nomor 2
rev_max = df['number_of_reviews'].idxmax()
print(df.loc[rev_max,'name'])

Luxuriously Spacious Studio Apt.

In [146]:
#nomor 3
min_night = df.sort_values(["minimum_nights"], ascending=[1])
min_night.head(n=5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
2766,19751695,Newly Refurbished Private Room @ Sembawang MRT,15035611,Anna,North Region,Sembawang,1.45111,103.82765,Private room,87,1,7,2017-12-16,0.28,1,0
6674,34244096,B1 • Minimalistic Room 5mins Train To MBS And ...,3234859,Sk,Central Region,Rochor,1.30324,103.86057,Private room,110,1,8,2019-08-17,2.31,9,138
2183,16640229,Brand New Cosy 2-Bedroom Apartment,109931020,Nyah,Central Region,Marine Parade,1.30101,103.89784,Entire home/apt,269,1,1,2017-01-20,0.03,1,0
4640,28116713,Terrace House @ Thomson Village,25375339,ｼﾝ,Central Region,Bishan,1.35389,103.83230,Entire home/apt,500,1,0,NaN,NaN,9,365
4639,28116308,Masteroom (bath) @ Terrace House @ Thomson Vil...,25375339,ｼﾝ,Central Region,Bishan,1.35266,103.83360,Private room,81,1,1,2018-10-03,0.09,9,362

In [147]:
#nomor 4
df.loc[df["host_name"] == "Jayce"]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
1890,15351390,Private Room near Paya Lebar&Dakota,78386666,Jayce,Central Region,Geylang,1.31150,103.89015,Private room,62,2,0,NaN,NaN,6,0
1950,15712633,Private Room near Paya Lebar MRT,78386666,Jayce,Central Region,Geylang,1.31476,103.88913,Private room,53,1,15,2018-10-03,0.45,6,0
2007,16027385,Private Common Room at near Paya Lebar MRT,78386666,Jayce,Central Region,Geylang,1.31728,103.88995,Private room,56,2,5,2018-04-30,0.17,6,0
2351,17677387,Private Master Room with attach bathroom,78386666,Jayce,Central Region,Geylang,1.31650,103.88944,Private room,56,1,2,2018-02-04,0.10,6,0
2513,18443344,Private Master Room w/Own Bathroom at paya lebar,78386666,Jayce,Central Region,Geylang,1.31449,103.89031,Private room,56,2,5,2019-01-01,0.29,6,0
2901,20446077,The condo common room at dakota mrt,78386666,Jayce,Central Region,Geylang,1.31193,103.88905,Private room,49,2,1,2018-01-23,0.05,6,0

In [148]:
#nomor 5
df['reviews_per_month'].corr(df['minimum_nights'])

-0.13946933876931453

ditemukan bahwa nilai korelasi hanya -0.13
bisa disimpulkan bahwa mereka berkorelasi terbalik secara sangat lemah